<?php
    $TENS = array('fa' => 'زمان', 'en' => 'Tens');
    $PAST = array('fa' => 'گذشته', 'en' => 'Past');
    $NOW = array('fa' => 'حال', 'en' => 'Now');
    $FUTURE = array('fa' => 'آینده', 'en' => 'Future');
    $ASSERTED = array('fa' => 'قطعی', 'en' => 'Asserted');
    $DEFINITIVE = array('fa' => 'قطعی', 'en' => 'Definitive');
    $UNCERTAIN = array('fa' => 'غیر قطعی', 'en' => 'Uncertain');
    $OTHER = array('fa' => 'غیر قطعی', 'en' => 'Other');
    $MODALITY = array('fa' => 'اطمینان از وقوع', 'en' => 'Modality');
    $POLARITY = array('fa' => 'قطبیت', 'en' => 'Polarity');
    $POSITIVE = array('fa' => 'مثبت', 'en' => 'Positive');
    $NEGATIVE = array('fa' => 'منفی', 'en' => 'Negative');
    $PROJECTS = array('fa' => 'پروژه‌ها', 'en' => 'Projects');
    $USERS = array('fa' => 'کاربران', 'en' => 'Users');
    $ENTITIES = array('fa' => 'موجودیت‌ها', 'en' => 'Entities');
    $EVENETS = array('fa' => 'رویداد‌ها', 'en' => 'Events');
    $STATISTICS = array('fa' => 'آمارها', 'en' => 'Statistics');
    $SETTINGS = array('fa' => 'تنظیمات', 'en' => 'Settings');
    $LOGOUT = array('fa' => 'خروج', 'en' => 'Logout');
    $CANCEL = array('fa' => 'لغو', 'en' => 'Cancel');
    $CONFIRM = array('fa' => 'تایید', 'en' => 'Confirm');
    $DELETE_THIS_EVENT = array('fa' => 'حذف رویداد', 'en' => 'Delete This Event');
    $DELETE_THIS_ENTITY = array('fa' => 'حذف موجودیت', 'en' => 'Delete This Entity');
    $LIST_OF_UNCERTIANS = array('fa' => 'شایعه،تهدید،خیال،خواستن،سوگند،ایده', 'en' => 'promise,dream,...');
    $LIST_OF_NEGATIVES = array('fa' => 'افعال‌منفی،کلمات‌جلوگیری‌کننده', 'en' => '');
    $ADD_USER = array('fa' => 'افزودن کاربر', 'en' => 'Add User');
    $ANNOTATE = array('fa' => 'تگ گذاری', 'en' => 'Annotate');
    $EXPORT = array('fa' => 'اکسل', 'en' => 'Export');
    $DELETE = array('fa' => 'حذف', 'en' => 'Delete');
    $START_ANNOTATION = array('fa' => 'شروع تگ گذاری', 'en' => 'Start Annotation');
    
